name: "Census of Bede Manuscripts"
description: "The website for the Census of Bede Manuscripts project, a collaborative effort to create a comprehensive listing of medieval manuscript copies of the works of the Venerable Bede."

url: "http://localhost:4000/"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments
contact-email: admin@bedemanuscripts.net

